package.json

fix: Fix build script

---

src/constants/code/TextAnimations/decryptedTextCode.js
src/content/TextAnimations/DecryptedText/DecryptedText.jsx
src/tailwind/TextAnimations/DecryptedText/DecryptedText.jsx

```
<DecryptedText
text="Secrets"
animateOn="view"
revealDirection="center"
/>
```
Doing this reserves space on the DOM but text not visible. I found this is the problem with `relative` positioning. Removing it fixes it.

Removing problematic position property from Decrypt text tailwind component 

---

src/constants/code/Animations/clickSparkCode.js
src/constants/code/Animations/crosshairCode.js
src/ts-default/Animations/ClickSpark/ClickSpark.tsx
src/ts-tailwind/Animations/ClickSpark/ClickSpark.tsx

**Description**
This pull request adds TypeScript support for the Click Spark component. As part of this effort, I've created TypeScript versions of the component, updated snippet constants, and modified the demo component to reflect the changes.
**Changes**
Created TypeScript versions of the Click Spark component:
Default version with CSS (/ts-default/ClickSpark)
Tailwind version (/ts-tailwind/ClickSpark)
Updated snippet constants in /src/constants/code/ClickSparkCode.js to include new TypeScript snippets
**Notes**
Followed branch naming convention: feat/add-ts-click-spark

 feat: added ts version for click-spark component 

---

src/constants/code/Animations/starBorderCode.js
src/ts-default/Animations/StarBorder/StarBorder.css
src/ts-default/Animations/StarBorder/StarBorder.tsx
src/ts-tailwind/Animations/StarBorder/StarBorder.tsx

This pull request adds TypeScript support for the `Animations/StarBorder` component. 
Created TypeScript version of the StarBorder component:
- Default version with CSS (`/ts-default/Animations/StarBorder`)
- Tailwind CSS version (`/ts-tailwind/Animations/StarBorder`)
- Updated snippet constants in `/src/constants/code/Animations/starBorderCode.js`
Followed branch naming convention: feat/add-ts-star-border

feat: add ts version for Animations/StarBorder component

---

src/constants/code/Backgrounds/wavesCode.js
src/ts-default/Backgrounds/Waves/Waves.css
src/ts-default/Backgrounds/Waves/Waves.tsx
src/ts-tailwind/Backgrounds/Waves/Waves.tsx

**Description**
This PR updates the Waves background component to be TypeScript-friendly, improving type safety and maintainability. The update includes the following changes:
**Changes**
- Refactored Waves.tsx in the ts-default and ts-tailwind directories to support TypeScript.
- Updated wavesCode.js in the constants directory for improved modularity.

feat: updated - waves background to ts-friendly component

---

src/constants/code/Backgrounds/squaresCode.js
src/demo/Backgrounds/SquaresDemo.jsx
src/ts-default/Backgrounds/Squares/Squares.css
src/ts-default/Backgrounds/Squares/Squares.tsx
src/ts-tailwind/Backgrounds/Squares/Squares.tsx

This pull request adds TypeScript support for the `Backgrounds/Squares` component.
Created TypeScript version of the Squares component:
- Default version with CSS (`/ts-default/Backgrounds/Squares`)
- Tailwind CSS version (`/ts-tailwind/Backgrounds/Squares`)
- Updated snippet constants in `/src/constants/code/Backgrounds/squaresCode.js`
- Updated `<CliInstallation />` props in `/src/demo/Backgrounds/SquaresDemo.jsx`
Followed branch naming convention: feat/add-ts-squares

feat: add ts version for Backgrounds/Squares component

---

src/constants/code/Components/spotlightCardCode.js
src/demo/Components/SpotlightCardDemo.jsx
src/ts-default/Components/SpotlightCard/SpotlightCard.css
src/ts-default/Components/SpotlightCard/SpotlightCard.tsx
src/ts-tailwind/Components/SpotlightCard/SpotlightCard.tsx

This pull request adds TypeScript support for the `Components/SpotlightCard` component.
Created TypeScript version of the SpotlightCard component:
- Default version with CSS (`/ts-default/Components/SpotlightCard`)
- Tailwind CSS version (`/ts-tailwind/Components/SpotlightCard`)
- Updated snippet constants in `/src/constants/code/Backgrounds/spotlightCardCode.js`
- Updated <CliInstallation /> props in `/src/demo/Components/SpotlightCardDemo.jsx`
Followed branch naming convention: feat/add-ts-spotlight-card
~~I will keep this in draft for now and wait for the previous PR to be merged. After that, I will rebase and wait for the review.~~
I confirmed that the previous PR was merged and rebased onto main.

feat: add ts version for Components/SpotlightCard component

---

jsrepo-build-config.json
package-lock.json
package.json

I pretty much just copy pasted the description and tags from github. 
Now when you look at the registry doc it should look like this (minus the localhost):

chore: Bump jsrepo + add metadata to the manifest

---

src/constants/code/Components/stackCode.js
src/demo/Components/StackDemo.jsx
src/tailwind/Components/Stack/Stack.jsx
src/ts-default/Components/Stack/Stack.css
src/ts-default/Components/Stack/Stack.tsx
src/ts-tailwind/Components/Stack/Stack.tsx

- Fix original Tailwind CSS version styles issue
- Add TS and TS + Tailwind CSS versions

Enhance Stack component 

---

src/constants/code/Backgrounds/hyperspeedCode.js
src/ts-default/Backgrounds/Hyperspeed/Hyperspeed.css
src/ts-default/Backgrounds/Hyperspeed/Hyperspeed.tsx

Changes:
Component Conversion:
- Created TypeScript versions of the Hyperspeed component:
- Default CSS version located at `/ts-default/Components/Backgrounda/Hyperspeed`.
Code Snippets Update:
Updated snippet constants in `/src/constants/code/Backgrounds/hyperSpeedCode.js` to reflect the new TypeScript implementations.

feat: implemented hyperspeed ts conversion

---

src/constants/code/Components/pixelCardCode.js
src/ts-default/Components/PixelCard/PixelCard.css
src/ts-default/Components/PixelCard/PixelCard.tsx
src/ts-tailwind/Components/PixelCard/PixelCard.tsx

Changes:
**Component Conversion:**
Created TypeScript versions of the PixelCard component:
- Default CSS version located at `/ts-default/Components/PixelCard`.
- Tailwind CSS version located at `/ts-tailwind/Components/PixelCard`.
**Code Snippets Update:**
Updated snippet constants in `/src/constants/code/Components/pixelCardCode.js` to reflect the new TypeScript implementations.

feat: added ts version of PixelCard

---

src/content/Animations/ClickSpark/ClickSpark.jsx
src/ts-default/Animations/ClickSpark/ClickSpark.tsx
src/ts-tailwind/Animations/ClickSpark/ClickSpark.tsx

fix: issue #88 fixed typos in both ts files, by copying from the js one

---

src/content/TextAnimations/ASCIIText/ASCIIText.jsx
src/demo/TextAnimations/ASCIITextDemo.jsx
src/tailwind/TextAnimations/ASCIIText/ASCIIText.jsx
src/ts-default/TextAnimations/ASCIIText/ASCIIText.tsx
src/ts-tailwind/TextAnimations/ASCIIText/ASCIIText.tsx

- added event listeners cleansing
- added animation frame cancellation
- added scene cleansing
- removed unused code
- removed warning text from "Ascii Text" demo page
Now the component is not laggy and you can easily change the props on demo page and see them in action.

fix: ASCIIText component disposal

---

src/constants/code/Components/infiniteScrollCode.js

fixed issue #110 !:))
positon -> position

fix-spelling-error for issue-#110

---

src/content/Animations/ClickSpark/ClickSpark.jsx
src/tailwind/Animations/ClickSpark/ClickSpark.jsx

This pull request enhances the ClickSpark component in both content and tailwind directories by adding support for rendering children elements and improving the component structure.
- ClickSpark component now accepts a children prop, allowing nested elements within the component.
- Implemented proper handling of child components while maintaining the spark animation effect.
- Wrapped the canvas element in a relative-positioned div to handle click events
- Added pointer-events-none to the canvas to ensure clicks pass through to children
- Maintained consistent styling across both implementations
- Added children prop to component parameters
- Updated return structure to include a wrapper div with relative positioning
- Adjusted canvas styling to use absolute positioning and …

Enhancement: Add children support to ClickSpark component in Javascript

---

src/tailwind/TextAnimations/BlurText/BlurText.jsx
src/ts-tailwind/TextAnimations/BlurText/BlurText.tsx

Resolving this issue: https://github.com/DavidHDev/react-bits/issues/152 
Smooth animation issue that reproduced on the tailwind version of BlurText component

fix: resolve BlurText TS Tailwind issue

---

src/content/Backgrounds/Hyperspeed/Hyperspeed.jsx
src/tailwind/Backgrounds/Hyperspeed/Hyperspeed.jsx
src/ts-default/Backgrounds/Hyperspeed/Hyperspeed.tsx
src/ts-tailwind/Backgrounds/Hyperspeed/Hyperspeed.tsx

Hyperspeed.jsx now listens to the onWindowResize event and adjust the renderer size with respect to the container size accordingly.

Update Hyperspeed: adjust renderer size as container size changes

---

src/ts-default/TextAnimations/SplitText/SplitText.tsx
src/ts-tailwind/TextAnimations/SplitText/SplitText.tsx

remove-any-on-SplitText

---

src/tailwind/Components/AnimatedList/AnimatedList.jsx
src/ts-tailwind/Components/AnimatedList/AnimatedList.tsx

Resolving this issue: #207 
When the value of displayScrollbar is false, the scroll bar will not be hidden.

fix: displayScrollbar=false not working in AnimatedList

---

src/ts-default/Components/PixelCard/PixelCard.tsx
src/ts-tailwind/Components/PixelCard/PixelCard.tsx

Is assigned as the return of requestAnimationFrame, so I typed accordingly (and I added a few "if is not null" before cancelling)
The `finalSpeed` (the first parameter is always a number, so no need to parse) and the second parameter is a boolean
I put each change in different commits just to be easier to validate, to merge can be squashed

Remove any from pixel card

---

src/ts-default/Components/RollingGallery/RollingGallery.tsx
src/ts-tailwind/Components/RollingGallery/RollingGallery.tsx

I checked the expected type and added it to the functions

remove any from RollingGallery

---

src/ts-default/Animations/ImageTrail/ImageTrail.tsx
src/ts-tailwind/Animations/ImageTrail/ImageTrail.tsx

Just another "any" removal 😎
By the way.... Is there some reason for variantMap to be an object with numerical indexes instead of an array?
If you want, I can refactor this in another MR
Best regards,
Pedro Almeida

remove any from ImageTrail

---

src/demo/Animations/CrosshairDemo.jsx

fixed unexpected several changes on linkText due to width of the text when its near the edge horizontally

react-bits/src/demo/Animation/CrosshairDemo.jsx

---

src/constants/code/Components/circularGalleryCode.js
src/content/Components/CircularGallery/CircularGallery.jsx
src/demo/Components/CircularGalleryDemo.jsx
src/tailwind/Components/CircularGallery/CircularGallery.jsx
src/ts-default/Components/CircularGallery/CircularGallery.tsx
src/ts-tailwind/Components/CircularGallery/CircularGallery.tsx

Adds scroll speed and easing controls to the CircularGallery component, allowing users to customize the scrolling behavior through props.
Closes #278
- **scrollSpeed prop**: Controls how much the gallery moves per scroll event (default: 2)
- **scrollEase prop**: Controls the smoothness of scroll transitions (default: 0.05)
- Interactive demo sliders for real-time scroll behavior testing
- `src/content/Components/CircularGallery/CircularGallery.jsx`
- `src/tailwind/Components/CircularGallery/CircularGallery.jsx`
- `src/ts-default/Components/CircularGallery/CircularGallery.tsx`
- `src/ts-tailwind/Components/CircularGallery/CircularGallery.tsx`
- `src/demo/Components/CircularGalleryDemo.jsx`
- `src/constants/code/Components/circularGalleryCode.js`
```jsx
// Slow, smooth scrolling …
```

feat: Add scroll speed control to CircularGallery component

---

src/content/TextAnimations/CountUp/CountUp.jsx
src/tailwind/TextAnimations/CountUp/CountUp.jsx
src/ts-default/TextAnimations/CountUp/CountUp.tsx
src/ts-tailwind/TextAnimations/CountUp/CountUp.tsx

Setting the "to" argument to a decimal value will add a float point while counting instead of rounding to the nearest number

feat: Added decimal numbers support

---

src/ts-default/Components/Masonry/Masonry.tsx
src/ts-tailwind/Components/Masonry/Masonry.tsx

Just removing another `any` to bot has lint issues when deployed on Vercel

remove-any-from-Masonry

---

src/content/Animations/TargetCursor/TargetCursor.jsx
src/tailwind/Animations/TargetCursor/TargetCursor.jsx
src/ts-default/Animations/TargetCursor/TargetCursor.tsx
src/ts-tailwind/Animations/TargetCursor/TargetCursor.tsx

Fixed the same problem I solved in [Vue Bits #84](https://github.com/DavidHDev/vue-bits/issues/84)

fix: Target cursor issue (from Vue Bits)
