DavidHDev/react-bits

- src/components/navs/Nav.jsx
Fix issue #4 
Increased the z-index of the navbar from 1 to 100.
**screenshots:**
> Fix issue 4 grid motion overlaps with navbar

- src/constants/code/Components/tiltedCardCode.js
- src/demo/Components/TiltedCardDemo.jsx
- src/ts-default/Components/TiltedCard/TiltedCard.css
- src/ts-default/Components/TiltedCard/TiltedCard.tsx
- src/ts-tailwind/Components/TiltedCard/TiltedCard.tsx
This pull request adds TypeScript support for the `Components/TiltedCard` component.
Created TypeScript version of the TiltedCard component:
- Default version with CSS (`/ts-default/Components/TiltedCard`)
- Tailwind CSS version (`/ts-tailwind/Components/TiltedCard`)
- Updated snippet constants in `/src/constants/code/Backgrounds/tiltedCardCode.js`
- Updated props in `/src/demo/Components/TiltedCardDemo.jsx`
Followed branch naming convention: `feat/add-ts-tilted-card`
> feat: add ts version for Components/TiltedCard component

- src/ts-default/Animations/ClickSpark/ClickSpark.tsx
- src/ts-tailwind/Animations/ClickSpark/ClickSpark.tsx
This pull request enhances the `ClickSpark` component in both `ts-default` and `ts-tailwind` directories by adding support for rendering children elements and improving the component structure.
1. **Added `children` prop**: 
- `ClickSpark` component now accepts a `children` prop of type `React.ReactNode`, allowing nested elements within the component.
2. **Updated component structure**:
- Replaced the `canvas` element with a `div` wrapper to handle click events and position the canvas absolutely within the div.
- Adjusted styles to ensure the canvas fills the parent div and does not interfere with pointer events.
- **`ClickSpark.tsx` (ts-default/Animations/ClickSpark)**:
- Added `children` prop to `ClickSparkProps`.
- Updated the `ClickSpark` component to render a `div` containing the …
> fix: type issue in click-spark component

- src/content/Animations/MetaBalls/MetaBalls.jsx
- src/tailwind/Animations/MetaBalls/MetaBalls.jsx
- src/ts-default/Animations/MetaBalls/MetaBalls.tsx
- src/ts-tailwind/Animations/MetaBalls/MetaBalls.tsx
Added transparency support to MetaBalls components across all implementations. Components now accept an `enableTransparency` prop that toggles between the default black background and a transparent background, allowing them to blend with underlying content.
- Added `enableTransparency` prop (default: false) to maintain backward compatibility
- Updated shader code to support dynamic transparency based on metaball field strength
- Modified renderer configuration to properly handle transparent backgrounds
- Implemented consistent behavior across all component versions:
- ts-default/Animations/MetaBalls
- ts-tailwind/Animations/MetaBalls
- content/Animations/MetaBalls
- tailwind/Animations/MetaBalls
#Video
https://drive.google.com/drive/folders/1lQi7VFyj8nkz3_vO7tNaVKbyio6-_uef?usp=sharing …
> [FEAT]: Add transparency support to MetaBalls components

- src/components/navs/Sidebar.jsx
- src/css/landing.css
While browsing the page, in the Docs section, I noticed a possible bug with the scroll bar. When playing with different viewport sizes, I found another issue on the landing page: the hero-content and stats-content sections were overlapping.
Before the changes:
After the changes:
> [FEAT]: Fixed some minor style issues 

- src/ts-default/TextAnimations/RotatingText/RotatingText.tsx
- src/ts-tailwind/TextAnimations/RotatingText/RotatingText.tsx
When I used the component RotatingText (TypeScript version) and deployed my project on Vercel, I was blocked in build due this error:
So I fixed and deploy went well (I just add the types from the lib, the same that the filed accept, so now the component prop reflects the lib types)
It is not a big deal, but can save 15 min of the next developer using this same component on Vercel
Note: It is only type related, so the Demo and tests will not got any changes, only linters 🙃
> fix-types-on-RotatingText-ts

- src/content/Backgrounds/Dither/Dither.jsx
- src/tailwind/Backgrounds/Dither/Dither.jsx
- src/ts-default/Backgrounds/Dither/Dither.tsx
- src/ts-tailwind/Backgrounds/Dither/Dither.tsx
This PR attempts to fix: https://github.com/DavidHDev/react-bits/issues/118
I honestly don't fully understand why this issue only occurred on Mac and not windows but I suspect it has to do with the handling of floating‑point math/ integer conversion. I also unfortunately don't fully understand why this solution works (on a high level, I changed the way the UV pixel was calculated and messed around with the colors until they resembled the original effect) but the you're free to play around with this code.
I was able to reproduce this bug on my Mac with Intel chip which suggests this bug wasn't only on Windows devices. I fixed the bug locally on the same device, I heavily suggest testing this on a Windows device first.
> Fix Dither

- src/constants/code/Animations/metallicPaintCode.js
In relation with this issue,  #167, the text from the import and the useState on the web
> fix: MetallicPaint import texts, and useState management

- src/ts-default/TextAnimations/VariableProximity/VariableProximity.tsx
- src/ts-tailwind/TextAnimations/VariableProximity/VariableProximity.tsx
The `...restProps` is applied on a span HTML tag, and on `forwardRef` is already correctly typed. So I updated the component interface (`VariableProximityProps`) to match with that.
Before:
After:
> type-VariableProximity-rest

- src/App.jsx
- src/components/code/CodeOptions.jsx
- src/components/context/LanguageContext/LanguageContext.jsx
- src/components/context/LanguageContext/useLanguage.js
- src/components/navs/Header.jsx
Before:
https://github.com/user-attachments/assets/19065704-5958-4902-bba4-b7e2a901b593
After:
https://github.com/user-attachments/assets/9622b897-80dc-433d-8dee-d3812de337a3
Note: The `localStorage.getItem('preferredLanguage') || 'JS';` was already on the code, so I just added the SET  when the user updates the option
> persist-preferredLanguage

- src/ts-default/TextAnimations/FuzzyText/FuzzyText.tsx
- src/ts-tailwind/TextAnimations/FuzzyText/FuzzyText.tsx
I just added the cleanupFuzzyText method on the canvaRef type, then the ANY before calling this method can be removed
> remove-any-on-FuzzyText

- src/ts-default/TextAnimations/DecryptedText/DecryptedText.tsx
- src/ts-tailwind/TextAnimations/DecryptedText/DecryptedText.tsx
Before
After
Note: for `src/ts-default/TextAnimations/DecryptedText/DecryptedText.tsx`, I follow the pattern of the tw component (I remove a child that it is part of the span props type, so it is all good
> remove any from DecryptedText

- src/ts-tailwind/Components/CircularGallery/CircularGallery.tsx
This pull request addresses an issue where the CircularGallery component was not rendering correctly due to a missing return statement within the component's function or render method. This typically results in the component not displaying any UI or potentially causing errors.
**Related Issue:** Closes #213
> Fix: Add missing return statement in CircularGallery component

- src/ts-default/TextAnimations/ScrollVelocity/ScrollVelocity.tsx
- src/ts-tailwind/TextAnimations/ScrollVelocity/ScrollVelocity.tsx
fixed issue #230 by updating the useElementWidth hook to use a generic type, resolving the ESLint strict type error.
> fix: update useElementWidth to support strict types (fixes #230)

- src/tailwind/TextAnimations/CircularText/CircularText.jsx
- src/ts-tailwind/TextAnimations/CircularText/CircularText.tsx
destination: src /tailwind/textAnimations/CircularText
-used tailwindcss to update the Circular Text component
-used the styles from the normal CSS component
PFA, screenshot from the local build.
> Fixed, BUG: text-animations/circular-text - Tailwind versions are broken #264

- src/content/Components/GooeyNav/GooeyNav.css
- src/content/Components/GooeyNav/GooeyNav.jsx
- src/tailwind/Components/GooeyNav/GooeyNav.jsx
- src/ts-default/Components/GooeyNav/GooeyNav.css
- src/ts-default/Components/GooeyNav/GooeyNav.tsx
- src/ts-tailwind/Components/GooeyNav/GooeyNav.tsx
While working on Issue #294, I initially explored enhancing navigation behavior by using the `useNavigate` hook from `react-router-dom` inside the `<li>`'s click handler. 
- It worked well for **route-based navigation**, but:
- ❌ It did **not support hash-based jumps** (e.g., `#about`, `#home`, `#contact`).
- Since `useNavigate` doesn't trigger anchor-style scrolling, this approach was dropped before submitting a PR.
---
After testing and refining, I went with a cleaner, style-based and DOM-structure approach that solves both navigation and animation issues:
- Moved `padding` from the `<li>` to the `<a>` tag.
- Applied `inline-block` to `<a>` so the entire visual area is now **clickable and navigable**, even for hash links.
- This uses native anchor behavior, which properly supports hash …
> [FIX}: Gooey Nav - Inconsistent Click and Navigation Behavior in <li> with Click Handlers and Styling

- src/content/Animations/Noise/Noise.jsx
- src/tailwind/Animations/Noise/Noise.jsx
- src/ts-default/Animations/Noise/Noise.tsx
- src/ts-tailwind/Animations/Noise/Noise.tsx
The Noise component has a critical memory leak causing 1GB/minute memory growth. Testing on the official React Bits website showed memory usage increasing from 400MB to 1.4GB within 60 seconds.
The implementation creates a new `CanvasPattern` object every 2 frames via `ctx.createPattern()`. These patterns aren't garbage collected properly, accumulating in memory indefinitely.
- **Firefox Dev Edition**: ~1GB/minute memory growth (most severe)
- **Chrome/Edge/Safari**: Slower initial growth (10-20s) then rapid acceleration
- All browsers eventually exhibit unbounded memory growth
- Fixed canvas size (1024x1024) scaled via CSS instead of using screen resolution
- Direct pixel manipulation with `putImageData()` instead of pattern creation
- Eliminates all pattern objects while preserving the …
> fix: memory leak in Noise component

- src/content/Backgrounds/DarkVeil/DarkVeil.jsx
- src/tailwind/Backgrounds/DarkVeil/DarkVeil.jsx
- src/ts-default/Backgrounds/DarkVeil/DarkVeil.tsx
- src/ts-tailwind/Backgrounds/DarkVeil/DarkVeil.tsx
Refactored the `start` variable declaration in the `DarkVeil` component by changing it from `let` to `const`.
- This change improves code safety and consistency, as the `start` variable is not reassigned after initialization.
- In some environments or with certain TypeScript/ESLint configurations, this may also resolve a minor type error or warning about variable mutability.
> refactor: change variable declaration from let to const for start in DarkVeil component

- src/constants/code/Components/profileCardCode.js
- src/content/Components/ProfileCard/ProfileCard.jsx
- src/demo/Components/ProfileCardDemo.jsx
- src/ts-default/Components/ProfileCard/ProfileCard.tsx
This pull request introduces a 3D tilt effect for the ProfileCard component on mobile devices, responding to the device's orientation.
The effect is triggered by the device's gyroscope and accelerometer data. To respect user privacy and browser security policies, the tilt
effect is only activated after the user clicks or taps on the card, which initiates the permission request for DeviceMotionEvent.
**Note**: As of the latest commit, this feature is only available on sites served over HTTPS, as DeviceMotionEvent requires a secure context in
most modern browsers.
- `ProfileCard.jsx` / `ProfileCard.tsx`:
- Added two new props:
- **enableMobileTilt** (boolean): To enable or disable the feature. Defaults to false.
- **mobileTiltSensitivity** (number): To control how much the card tilts in …
> Feat/Add mobile device tilt support to ProfileCard

- src/content/Backgrounds/Dither/Dither.jsx
- src/tailwind/Backgrounds/Dither/Dither.jsx
- src/ts-default/Backgrounds/Dither/Dither.tsx
- src/ts-tailwind/Backgrounds/Dither/Dither.tsx
```glsl
- const int OCTAVES = 8;
+ const int OCTAVES = 4;
```
🧠 Cuts number of `cnoise()` calls in half — big shader win.
---
```glsl
- return fbm(p - fbm(p + fbm(p2)));
+ return fbm(p + fbm(p2));
```
Reduced expensive nested FBM calls.
---
```tsx
// Before
u.waveColor.value.set(...waveColor);
// After
if (!prevColor.every((v, i) => v === waveColor[i])) {
u.waveColor.value.set(...waveColor);
prevColor = [...waveColor];
}
```
---
```tsx
- const [mousePos, setMousePos] = useState(...);
+ const mouseRef = useRef(new THREE.Vector2());
// useFrame
u.mousePos.value.copy(mouseRef.current);
```
Prevents re-renders per second on pointer move.
---
```tsx
if (u.waveSpeed.value !== waveSpeed) u.waveSpeed.value = waveSpeed;
if (u.waveFrequency.value !== waveFrequency) u.waveFrequency.value = …
```
> feat: optimize dither backgrounds

- src/ts-default/TextAnimations/TextTrail/TextTrail.tsx
- src/ts-tailwind/TextAnimations/TextTrail/TextTrail.tsx
The `document` object has the right type already, no need for "any"  😎
Before
After
> feat: remove unnecessary any type assertion in TextTrail component

- src/content/Animations/Cubes/Cubes.jsx
- src/tailwind/Animations/Cubes/Cubes.jsx
- src/ts-default/Animations/Cubes/Cubes.tsx
- src/ts-tailwind/Animations/Cubes/Cubes.tsx
This PR implements mobile touch support for the Cubes component, addressing the feature request to provide consistent cross-device interaction.
https://github.com/user-attachments/assets/5284292b-dabc-48f9-af96-17a14a96d1e7
- Added dedicated touch event handlers (`touchmove`, `touchstart`, `touchend`)
- Enhanced click handler to support both mouse and touch events
- Implemented proper touch coordinate mapping for tilt interactions
- Added preventDefault to avoid unwanted scroll behavior during touch
- Applied changes consistently across all 4 component variants
- **Touch Events**: Maps touch coordinates to existing tilt logic for seamless mobile interaction
- **Backward Compatibility**: All existing mouse functionality remains unchanged
- **Cross-Variant Support**: Applied to JS/TS + …
> feat: add mobile touch support for Cubes component

- src/content/TextAnimations/TextType/TextType.jsx
- src/tailwind/TextAnimations/TextType/TextType.jsx
- src/ts-default/TextAnimations/TextType/TextType.tsx
- src/ts-tailwind/TextAnimations/TextType/TextType.tsx
The `getRandomSpeed` function was being created on every render, and the `textArray` variable was being recalculated on every render. This wraps `textArray` in a `useMemo` hook and wraps `getRandomSpeed` in a `useCallback` hook to improve the performance of the component.
> TextType: add useMemo and useCallback to improve performance

- src/components/landing/PlasmaWave/PlasmaWaveV2.jsx
- src/content/Backgrounds/LetterGlitch/LetterGlitch.jsx
This PR fixes server crashes caused by missing ref objects in two components:
•	PlasmaWaveV2: Added null check for rendererRef.
•	LetterGlitch: Added null check for canvasRef.
Previously, when either rendererRef or canvasRef was null, the server would crash unexpectedly. With these changes, both components now safely exit early if the ref is not available.
Closes #406
> Fix: Add null checks for rendererRef and canvasRef to prevent server crash

- src/content/Backgrounds/GridDistortion/GridDistortion.jsx
- src/demo/Backgrounds/GridDistortionDemo.jsx
- src/tailwind/Backgrounds/GridDistortion/GridDistortion.jsx
- src/ts-default/Backgrounds/GridDistortion/GridDistortion.tsx
- src/ts-tailwind/Backgrounds/GridDistortion/GridDistortion.tsx
This pull request significantly refactors and improves the `GridDistortion` background component across the default, Tailwind, and TypeScript implementations. The main focus is on enhancing rendering performance, responsiveness, and resource management by modernizing the Three.js setup, improving resize handling, and ensuring proper cleanup. Additionally, it improves visual quality and robustness of the distortion effect.
**Refactoring and Modernization:**
* Replaces single-use refs with multiple refs (`sceneRef`, `rendererRef`, `planeRef`, etc.) for better management of Three.js objects and animation state, and removes unused `initialDataRef`. [[1]](diffhunk://#diff-d86db0af0943fac4bb2b1cb380ad8d89f509c3fe8c3025d0c5cfbfcdb6e4637fL37-R67) …
> Refactor and Enhance GridDistortion Component: Modernization, Responsiveness, and Resource Management #408

- src/ts-default/Backgrounds/LetterGlitch/LetterGlitch.tsx
- src/ts-tailwind/Backgrounds/LetterGlitch/LetterGlitch.tsx
Renames `m` to `_m` in replace callback to indicate intentional non-use and avoid TS `noUnusedParameters` warning.
> fix: suppress unused parameter warning in hex shorthand

- src/ts-default/Backgrounds/Prism/Prism.tsx
- src/ts-tailwind/Backgrounds/Prism/Prism.tsx
Introduced a PrismContainer interface to type the __prismIO property on HTMLElement, replacing previous use of 'any' casting. This improves type safety when attaching and removing the IntersectionObserver instance used for offscreen suspension.
> fix: Add PrismContainer interface for IntersectionObserver

- src/content/Animations/LaserFlow/LaserFlow.jsx
- src/tailwind/Animations/LaserFlow/LaserFlow.jsx
- src/ts-default/Animations/LaserFlow/LaserFlow.tsx
- src/ts-tailwind/Animations/LaserFlow/LaserFlow.tsx
**🐛 Fix Safari fog fade issue and optimize LaserFlow performance**
**Issue**
Fixes #476 - Safari fog fadeoff effect fails, causing solid fog appearance instead of proper fade properties. Also addresses performance issues with unstable framerate and lag spikes.
**Problem Description**
- Safari: Fog effect appears as solid, opaque mass without proper fade-off
- Performance: Unstable framerate and lag spikes across all browsers
- Cross-browser: Inconsistent fog visibility after Safari-specific fixes
**Solution**
**🔧 Safari Fog Fix**
- Implemented Safari-compatible radial fade calculation using distance-based attenuation
- Added browser-specific fog intensity multiplier for cross-browser consistency
- Adjusted fog contrast and mask gamma for optimal Safari rendering
**⚡ Performance …
> 🐛 Fix Safari fog fade issue and optimize LaserFlow performance
